[versions]
about-libraries = "13.1.0"
android-gradle-plugin = "8.13.1"
android-compileSdk = '36'
android-minSdk = '23'
androidx-lifecycle = '2.10.0'
compose = '1.9.5'
coil = '3.3.0'
koin = '4.1.1'
koin-annotation= "2.3.1"
kotlin = '2.2.21'
kotlinx-coroutines = '1.10.2'
ksp-compiler = '2.3.3'
ktor = '3.2.3' # Version 3.3+ requires OkHttp 5+
media3 = '1.8.0'
okhttp = '4.12.0'
room = '2.7.2'
sentry-android = '7.22.6'
workmanager = '2.11.0'

[libraries]

aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "about-libraries" }
androidx-activity-compose = 'androidx.activity:activity-compose:1.12.0'
androidx-core-ktx = 'androidx.core:core-ktx:1.17.0'
androidx-datastore-core = 'androidx.datastore:datastore:1.0.0'
androidx-documentfile ='androidx.documentfile:documentfile:1.1.0'
androidx-lifecycle-process = { module = 'androidx.lifecycle:lifecycle-process', version.ref = 'androidx-lifecycle' }
androidx-lifecycle-runtime-compose = { module = 'androidx.lifecycle:lifecycle-runtime-compose', version.ref = 'androidx-lifecycle' }
androidx-lifecycle-service = { module = 'androidx.lifecycle:lifecycle-service', version.ref = 'androidx-lifecycle' }
androidx-lifecycle-viewmodel = { module = 'androidx.lifecycle:lifecycle-viewmodel', version.ref = 'androidx-lifecycle' }
androidx-media3-exoplayer = { module = 'androidx.media3:media3-exoplayer', version.ref = 'media3' }
androidx-media3-session = { module = 'androidx.media3:media3-session', version.ref = 'media3' }
androidx-media3-test-utils = { module = 'androidx.media3:media3-test-utils', version.ref = 'media3' }
androidx-media3-test-utils-robolectric = { module = 'androidx.media3:media3-test-utils-robolectric', version.ref = 'media3' }
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.9.6"
androidx-room-compiler = { module = 'androidx.room:room-compiler', version.ref = 'room' }
androidx-room-ktx = { module = 'androidx.room:room-ktx', version.ref = 'room' }
androidx-room-testing = { module = 'androidx.room:room-testing', version.ref = 'room' }
androidx-test-corektx = 'androidx.test:core-ktx:1.7.0'
androidx-test-junit = 'androidx.test.ext:junit:1.3.0'
androidx-window = 'androidx.window:window:1.5.1'
androidx-workmanager-ktx = { module = 'androidx.work:work-runtime-ktx', version.ref = 'workmanager' }

compose-material3 = 'androidx.compose.material3:material3:1.4.0'
compose-ui-ui = { module = 'androidx.compose.ui:ui', version.ref = 'compose' }
compose-ui-test-junit = { module = 'androidx.compose.ui:ui-test-junit4', version.ref = 'compose' }
compose-ui-test-manifest = { module = 'androidx.compose.ui:ui-test-manifest', version.ref = 'compose' }
compose-ui-tooling = { module = 'androidx.compose.ui:ui-tooling', version.ref = 'compose' }
compose-ui-tooling-preview = { module = 'androidx.compose.ui:ui-tooling-preview', version.ref = 'compose' }

coil-compose = { module = 'io.coil-kt.coil3:coil-compose', version.ref = 'coil' }
coil-okhttp = { module = 'io.coil-kt.coil3:coil-network-okhttp', version.ref = 'coil' }

desugarjdk = 'com.android.tools:desugar_jdk_libs:2.1.5'

koin-android = { module = 'io.insert-koin:koin-android', version.ref = 'koin' }
koin-androidx-compose = { module = 'io.insert-koin:koin-androidx-compose', version.ref = 'koin' }
koin-annotations = { module = 'io.insert-koin:koin-annotations', version.ref = 'koin-annotation' }
koin-compiler = { module = 'io.insert-koin:koin-ksp-compiler', version.ref = 'koin-annotation' }
koin-test-junit4 = { module = 'io.insert-koin:koin-test-junit4', version.ref = 'koin' }

kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

kotlinx-coroutines-android = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-android', version.ref = 'kotlinx-coroutines' }
kotlinx-coroutines-guava = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-guava', version.ref = 'kotlinx-coroutines' }
kotlinx-coroutines-test = { module = 'org.jetbrains.kotlinx:kotlinx-coroutines-test', version.ref = 'kotlinx-coroutines' }

kotlinx-serialization-json = { module = 'org.jetbrains.kotlinx:kotlinx-serialization-json', version = '1.9.0' }

ktor-okhttp = { module = 'io.ktor:ktor-client-okhttp', version.ref = 'ktor' }

okhttp = { module = 'com.squareup.okhttp3:okhttp', version.ref = 'okhttp' }
okhttp-tls = { module = 'com.squareup.okhttp3:okhttp-tls', version.ref = 'okhttp' }

podcastindex = 'io.github.mr3y-the-programmer:podcastindex-sdk-ktor3:0.4.0'
rssparser = 'com.prof18.rssparser:rssparser:6.0.12'

sentry-android = { module = 'io.sentry:sentry-android', version.ref = 'sentry-android' }
sentry-android-timber = { module = 'io.sentry:sentry-android-timber', version.ref = 'sentry-android' }

timber = 'com.jakewharton.timber:timber:5.0.1'
telemetrydeck = 'com.telemetrydeck:kotlin-sdk:6.2.2'
treessence = 'com.github.bastienpaulfr:Treessence:1.1.2'

junit = 'junit:junit:4.13.2'
robolectric = 'org.robolectric:robolectric:4.16'
turbine = 'app.cash.turbine:turbine:1.2.1'


[plugins]
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about-libraries" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = 'org.jetbrains.kotlin.android', version.ref = 'kotlin' }
kotlin-serialization = { id = 'org.jetbrains.kotlin.plugin.serialization', version.ref = 'kotlin' }
ksp = { id = 'com.google.devtools.ksp', version.ref = 'ksp-compiler' }
room = { id = 'androidx.room', version.ref = 'room' }
sentry = 'io.sentry.android.gradle:4.3.1'
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }